#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# Check if the "0" directory exists and remove it
if [ -d "0" ]; then
    echo "Removing folder '0'"
    rm -r "0"
fi

#------------------------------------------------------------------------------
