#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

cp -r 0.orig 0

runApplication blockMesh

# Get the current folder name
caseName=${PWD##*/}

# Create the .foam file with the folder name
touch "${caseName}.foam"

# =============== Run serial ===============
#runApplication $application
#runApplication foamToVTK


# ============== Run parallel ==============

runApplication decomposePar

for dir in processor*/; do
  if [ -d "$dir" ]; then # Check if it's indeed a directory
    # Ensure the 'constant' subdirectory exists
    mkdir -p "${dir}constant/Positions"
    mkdir -p "${dir}constant/Samples"
    # Copy all files starting with 'Samples' into the 'constant' subdirectory
    cp -r constant/Samples/Sample "${dir}constant/Samples"
  fi
done

runParallel $application
runApplication reconstructPar
runApplication foamToVTK
rm -r processor*

#------------------------------------------------------------------------------
